namespace: deploy
containers:
  app:
    image: perennial/deploy:{{.branch}}
    volumes:
      - {{.apps}}:/apps
    {{if eq .env "dev"}}
      - {{.root}}/config.yml:/app/config.yml
    {{end}}
    ports:
      - 1337:80