credentials:
  github:
    Perennials:
      token: xxxxxxxxxxx
      username: perennials-bot
      password: xxxxxxxxxx

vars:
  env: dev

projects:

  ####
  docker:
    #repo:
    #  remote: github/Perennials/docker
    #  local: {project.local}

    #docker: !yamlfifle '{project.local}/deploy.yml'

    docker:
      - image: docker.perennial.int/supplier2
        path: git@github.com:Perennials/docker#:/supplier2
      - image: docker.perennial.int/php:5.4
        path: git@github.com:Perennials/docker#:/php54
      - image: docker.perennial.int/nginx2
        path: git@github.com:Perennials/docker#:/nginx2

    vars:
      local: /apps/docker

  ####
  bonotel:
    extends: supplier

    rocker-compose:
      vars:
        port: 20011

  ####
  ws2:
    branches: [ 'master', !!js/regexp '^\d+\.\d+$' ]
    repo:
      remote: github/Perennials/providersdk-ws
      local: /apps/{project}/{branch}

    docker:
      image: 'docker.perennial.int/{project}:{branch.tag}'
      file: '{project.local}/docker'

  ####
  supplier:
    template: true

    vars:
      local: /apps/supplier/{project}/{branch}
      config: /config/supplier/{project}/{branch}
      config-common: /config/supplier/_common/{project.sdk-version}
      sdk-version: !!js/function >
        function ( global, require, vars ) {
          try {
            return require( 'fs' )
              .readFileSync( vars.render( '{project.local}/supplier.php' ), 'utf8' )
              .match( /providerkit-php\/([^\/]+)\/init.php/ )[ 1 ];
          }
          catch ( e ) {
            // global.console.error( e );
            // global.console.log( vars )
            return 'master';
          }
        }

    ################### this should go in include only for dev
    #extends: !yamlfile /config/deploy/supplier.{env}.yml
    repo:
      remote: github/Perennials/supplier-{project}
      local: '{project.local}'
      submodules:
        github/Perennials/providerkit-php#{project.sdk-version}: '{project.local}/lib/providerkit-php'

    docker:
      image: 'docker.perennial.int/{project}:{branch.tag}'
      path: '{project.local}'
    ###################

    rocker-compose:
      path: '{project.config-common}'
      vars:
        env: '{env}'
        name: '{project}'
        version: '{branch}'
        version_tag: '{branch.tag}'
        version_flat: '{branch.flat}'

    